// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamWorkflowLifecycleState } from "./TeamWorkflowLifecycleState";
import type { TeamWorkflowPhase } from "./TeamWorkflowPhase";

export type TeamWorkflowLifecycle = { state: TeamWorkflowLifecycleState, phase: TeamWorkflowPhase, reviewRequired: boolean, blocked: boolean, integrationReady: boolean, traceGroupId: string, lastTransitionAt: string, };
