// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamWorkflowMemoryProviderHealth } from "./TeamWorkflowMemoryProviderHealth";
import type { TeamWorkflowMemoryProviderMode } from "./TeamWorkflowMemoryProviderMode";

export type TeamWorkflowMemoryProvider = { mode: TeamWorkflowMemoryProviderMode, health: TeamWorkflowMemoryProviderHealth, };
