// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamWorkflowHandoff } from "./TeamWorkflowHandoff";
import type { TeamWorkflowLifecycle } from "./TeamWorkflowLifecycle";
import type { TeamWorkflowMemoryProvider } from "./TeamWorkflowMemoryProvider";
import type { TeamWorkflowPhase } from "./TeamWorkflowPhase";
import type { TeamWorkflowRootAgent } from "./TeamWorkflowRootAgent";

export type TeamWorkflowSession = { rootThreadId: string, rootTeamId: string, rootRole: string, rootAgent: TeamWorkflowRootAgent, lifecycle: TeamWorkflowLifecycle, handoff: TeamWorkflowHandoff, currentPhase: TeamWorkflowPhase, maxDepth: number, activeTeamCount: number, blockedTeamCount: number, staleResourceCount: number, memoryProvider: TeamWorkflowMemoryProvider, globalGovernancePath: string, teamStateIndexPath: string, updatedAt: string, };
