// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamWorkflowLifecycleState } from "./TeamWorkflowLifecycleState";

export type TeamWorkflowHandoff = { state: TeamWorkflowLifecycleState, activeDelegateCount: number, blockedDelegateCount: number, awaitingReviewCount: number, integrationReadyCount: number, traceGroupId: string, };
